export enum actionTypes {
    RECOMMEND_EDIT_UPDATE_STARTED = 'RECOMMEND_EDIT_UPDATE_STARTED',
    RECOMMEND_EDIT_UPDATE_SUCCESS = 'RECOMMEND_EDIT_UPDATE_SUCCESS',
    RECOMMEND_EDIT_UPDATE_FAILURE = 'RECOMMEND_EDIT_UPDATE_FAILURE',
    RECOMMEND_EDIT_SHOW_STARTED = 'RECOMMEND_EDIT_SHOW_STARTED',
    RECOMMEND_EDIT_SHOW_FAILURE = 'RECOMMEND_EDIT_SHOW_FAILURE',
    RECOMMEND_EDIT_SHOW_SUCCESS = 'RECOMMEND_EDIT_SHOW_SUCCESS',
    RECOMMEND_EDIT_CACHE = 'RECOMMEND_EDIT_CACHE'
}
