export enum actionTypes {
    // 编辑文章获取文章动作
    EDIT_GET_ARTICLE_STARTED = 'EDIT_GET_ARTICLE_STARTED',
    EDIT_GET_ARTICLE_SUCCESS = 'EDIT_GET_ARTICLE_SUCCESS',
    EDIT_GET_ARTICLE_FAILURE = 'EDIT_GET_ARTICLE_FAILURE',
    // 编辑文章发送请求修改文章动作
    EDIT_UPDATE_ARTICLE_STARTED = 'EDIT_UPDATE_ARTICLE_STARTED',
    EDIT_UPDATE_ARTICLE_SUCCESS = 'EDIT_UPDATE_ARTICLE_SUCCESS',
    EDIT_UPDATE_ARTICLE_FAILURE = 'EDIT_UPDATE_ARTICLE_FAILURE',
    EDIT_CACHE_ARTICLE = 'EDIT_CACHE_ARTICLE'
}
