export enum actionTypes {
    // recommend articles list get action
    RECOMMENDS_GET_LIST_STARTED = 'RECOMMENDS_GET_LIST_STARTED',
    RECOMMENDS_GET_LIST_FAILURE = 'RECOMMENDS_GET_LIST_FAILURE',
    RECOMMENDS_GET_LIST_SUCCESS = 'RECOMMENDS_GET_LIST_SUCCESS',

    // recommend article delete action
    RECOMMEND_DELETE_STARTED = 'RECOMMEND_DELETE_STARTED',
    RECOMMEND_DELETE_FAILURE = 'RECOMMEND_DELETE_FAILURE',
    RECOMMEND_DELETE_SUCCESS = 'RECOMMEND_DELETE_SUCCESS'
}
