export enum actionTypes {
    // 推荐列表获取
    RECOMMENDS_GET_LIST_STARTED = 'RECOMMENDS_GET_LIST_STARTED',
    RECOMMENDS_GET_LIST_FAILURE = 'RECOMMENDS_GET_LIST_FAILURE',
    RECOMMENDS_GET_LIST_SUCCESS = 'RECOMMENDS_GET_LIST_SUCCESS'
}
