export enum actionTypes {
    CATEGORY_CREATE_POST_STARTED = 'CATEGORY_CREATE_POST_STARTED',
    CATEGORY_CREATE_POST_FAILURE = 'CATEGORY_CREATE_POST_FAILURE',
    CATEGORY_CREATE_POST_SUCCESS = 'CATEGORY_CREATE_POST_SUCCESS',
    CATEGORY_CREATE_SET_CACHE = 'CATEGORY_CREATE_SET_CACHE'
}
