export enum actionTypes {
    EDIT_GET_ARTICLE_STARTED = 'EDIT_GET_ARTICLE_STARTED',
    EDIT_GET_ARTICLE_SUCCESS = 'EDIT_GET_ARTICLE_SUCCESS',
    EDIT_GET_ARTICLE_FAILURE = 'EDIT_GET_ARTICLE_FAILURE',
    EDIT_UPDATE_ARTICLE_STARTED = 'EDIT_UPDATE_ARTICLE_STARTED',
    EDIT_UPDATE_ARTICLE_SUCCESS = 'EDIT_UPDATE_ARTICLE_SUCCESS',
    EDIT_UPDATE_ARTICLE_FAILURE = 'EDIT_UPDATE_ARTICLE_FAILURE'
}
