export enum actionTypes {
    // CATEGORY 管理获取当前 CATEGORY
    CATEGORY_GET_LIST_STARTED = 'CATEGORY_GET_LIST_STARTED',
    CATEGORY_GET_LIST_FAILURE = 'CATEGORY_GET_LIST_FAILURE',
    CATEGORY_GET_LIST_SUCCESS = 'CATEGORY_GET_LIST_SUCCESS'
}
