export enum actionTypes {
    CREATE_ARTICLE_STARTED = 'CREATE_ARTICLE_STARTED',
    CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE',
    CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS',
    CREATE_ARTICLE_SET_CACHE = 'CREATE_ARTICLE_SET_CACHE',
    CREATE_ARTICLE_GET_CACHE = 'CREATE_ARTICLE_GET_CACHE',
    CREATE_ARTICLE_GET_ATEGORY_STARTED = 'CREATE_ARTICLE_GET_ATEGORY_STARTED',
    CREATE_ARTICLE_GET_ATEGORY_FAILURE = 'CREATE_ARTICLE_GET_ATEGORY_FAILURE',
    CREATE_ARTICLE_GET_ATEGORY_SUCCESS = 'CREATE_ARTICLE_GET_ATEGORY_SUCCESS'
}
