export enum actionTypes {
    CATEGORY_EDIT_POST_STARTED = 'CATEGORY_EDIT_POST_STARTED',
    CATEGORY_EDIT_POST_FAILURE = 'CATEGORY_EDIT_POST_FAILURE',
    CATEGORY_EDIT_POST_SUCCESS = 'CATEGORY_EDIT_POST_SUCCESS',
    CATEGORY_EDIT_GET_STARTED = 'CATEGORY_EDIT_GET_STARTED',
    CATEGORY_EDIT_GET_FAILURE = 'CATEGORY_EDIT_GET_FAILURE',
    CATEGORY_EDIT_GET_SUCCESS = 'CATEGORY_EDIT_GET_SUCCESS',
    CATEGORY_EDIT_FEATURED_STARTED = 'CATEGORY_EDIT_FEATURED_STARTED',
    CATEGORY_EDIT_FEATURED_FAILURE = 'CATEGORY_EDIT_FEATURED_FAILURE',
    CATEGORY_EDIT_FEATURED_SUCCESS = 'CATEGORY_EDIT_FEATURED_SUCCESS',
    CATEGORY_EDIT_CACHE_SUCCESS = 'CATEGORY_EDIT_CACHE_SUCCESS'
}
