export enum actionTypes {
    // 推荐列表获取
    RECOMMEND_POST_CREATE_STARTED = 'RECOMMEND_POST_CREATE_STARTED',
    RECOMMEND_POST_CREATE_FAILURE = 'RECOMMEND_POST_CREATE_FAILURE',
    RECOMMEND_POST_CREATE_SUCCESS = 'RECOMMEND_POST_CREATE_SUCCESS'
}
