export enum actionTypes {
    HOME_GET_ARTICLES_STARTED = 'HOME_GET_ARTICLES_STARTED',
    HOME_GET_ARTICLES_SUCCESS = 'HOME_GET_ARTICLES_SUCCESS',
    HOME_GET_ARTICLES_FAILURE = 'HOME_GET_ARTICLES_FAILURE',
    // 删除文章
    HOME_DELETE_ARTILCE_STARTED = 'HOME_DELETE_ARTILCE_STARTED',
    HOME_DELETE_ARTICLE_SUCCESS = 'HOME_DELETE_ARTICLE_SUCCESS',
    HOME_DELETE_ARTICLE_FAILURE = 'HOME_DELETE_ARTICLE_FAILURE',
    // 废弃文章
    HOME_DISCARD_ARTICLE_STARTED = 'HOME_DISCARD_ARTICLE_STARTED',
    HOME_DISCARD_ARTICLE_SUCCESS = 'HOME_DISCARD_ARTICLE_SUCCESS',
    HOME_DISCARD_ARTICLE_FAILURE = 'HOME_DISCARD_ARTICLE_FAILURE'
}
