export enum actionTypes {
    HOME_GET_ARTICLES_STARTED = 'HOME_GET_ARTICLES_STARTED',
    HOME_GET_ARTICLES_SUCCESS = 'HOME_GET_ARTICLES_SUCCESS',
    HOME_GET_ARTICLES_FAILURE = 'HOME_GET_ARTICLES_FAILURE'
}
