export enum actionTypes {
    COMPONENT_SUGGESTION_GET_STARTED = 'COMPONENT_SUGGESTION_GET_STARTED',
    COMPONENT_SUGGESTION_GET_FAILURE = 'COMPONENT_SUGGESTION_GET_FAILURE',
    COMPONENT_SUGGESTION_GET_SUCCESS = 'COMPONENT_SUGGESTION_GET_SUCCESS'
}
